### ISSUE TITLE
How minute step fixed on 5

### ISSUE THREAD

**Issue by Slinf** [weareoutman/clockpicker#73] opened 2016-02-10 09:26 UTC
Hi, i would fixed a step 5 by 5 min , like the minute on the display not between like 16min or 54 just 05-00-05-10-15-20-25-30-35-40-45-50-55-. I search in jquery.clockpicker-min.js  but its hard; If anybody know how//

i have check he other post on 30 minute step and doesb't run for me

Thanks

**Comment by patapron** [comment] 2016-03-29 13:39
+1

**Comment by Chrumo** [comment] 2016-04-04 14:35
+1

**Comment by PhiLhoSoft** [comment] 2016-09-12 13:59
Duplicate of #51

**Closed as completed** 2017-03-28 19:12 UTC
